select = [
    # Pyflakes checks
    "F",
    # Prohibit tabs:
    "W191",
    # No trailing whitespace:
    "W291",
    "W293",
    # Make sure we bind closure variables in a loop (equivalent to pylint
    # cell-var-from-loop):
    "B023",
    # Don't use mutable default arguments:
    "B006",
]